In [ ]:
## This is to show that Logistic Regression , does not work for simple classification , like even and odd numbers

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

# Generate data: natural numbers 1 to 100
X = np.arange(1, 101).reshape(-1, 1)
y = X % 2  # 0 = even, 1 = odd

# Split into train/test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train Logistic Regression
model = LogisticRegression()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate
accuracy = accuracy_score(y_test, y_pred)
print("Predictions:", y_pred)
print("Accuracy:", accuracy)
print("Weights (coef):", model.coef_)
print("Intercept:", model.intercept_)


Predictions: [1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0]
Accuracy: 0.4
Weights (coef): [[0.00394728]]
Intercept: [-0.30468185]


/Users/zainabfirdaus/git/airflow/.venv/lib/python3.9/site-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [2]:
X_val = np.arange(101, 111).reshape(-1, 1)
y_val = X_val % 2
y_val_pred = model.predict(X_val)
accuracy = accuracy_score(y_val, y_val_pred)
print("Validation predictions:", y_val_pred)
print("Validation accuracy:", accuracy)
print("Weights (coef):", model.coef_)
print("Intercept:", model.intercept_)

Validation predictions: [1 1 1 1 1 1 1 1 1 1]
Validation accuracy: 0.5
Weights (coef): [[0.00394728]]
Intercept: [-0.30468185]


In [10]:
my_X_val=np.array([120,122,124,126,128]).reshape(-1, 1)
type(my_X_val)

numpy.ndarray

In [7]:
print(type(X_val))

<class 'numpy.ndarray'>


In [11]:
pred11=model.predict(my_X_val)

In [12]:
pred11

array([1, 1, 1, 1, 1])

In [13]:
my_X_val2=np.array([121,123,125,127,129])

In [19]:
pred12=model.predict(my_X_val2)

In [16]:
my_X_val2 

array([121, 123, 125, 127, 129])

In [17]:
my_X_val2=my_X_val2.reshape(-1,1)

In [18]:
my_X_val2 

array([[121],
       [123],
       [125],
       [127],
       [129]])

In [20]:
pred12

array([1, 1, 1, 1, 1])

In [21]:
my_X_val3=np.array([131,132,133,134,129]).reshape(-1,1)
pred13 = model.predict(my_X_val3)
pred13

array([1, 1, 1, 1, 1])

In [22]:
my_X_val4=np.array([1,2,3,4,5]).reshape(-1,1)
pred14 = model.predict(my_X_val4)
pred14

array([0, 0, 0, 0, 0])

In [23]:
X = np.arange(1, 11).reshape(-1, 1)  # shape (10,1)
y = X % 2  # 0 = even, 1 = odd

# Train Logistic Regression
model = LogisticRegression()
model.fit(X, y)

# Make predictions on the same data
y_pred = model.predict(X)

/Users/zainabfirdaus/git/airflow/.venv/lib/python3.9/site-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [24]:
X

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [25]:
y

array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0]])

In [26]:
y_pred

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])